---
on:
  push:
    branches:
      - master
    paths:
      - 'ide/docker/**'
      - 'ide/provisioning/**'
      - '.github/workflows/build-container.yml'
  release:
    types: [published]

jobs:
  xcsoar-docker-env:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}

      - name: Determine Docker Tag
        id: determine_tag
        run: |
          if [[ ${{ github.ref }} == 'refs/tags/v'* ]]; then
            echo "v${{ github.ref }}" >> $GITHUB_ENV
          else
            echo "latest" >> $GITHUB_ENV
          fi

      - name: Build and Push Docker Container
        uses: docker/build-push-action@v2
        with:
          context: ./ide
          file: ./ide/docker/Dockerfile
          tags: |
            ghcr.io/${{ github.repository_owner }}/xcsoar-build:${{ steps.determine_tag.outputs.value }}
          push: true
