on:
  workflow_dispatch:
  push:
    paths:
      - ./ide/docker/
      - ./ide/provisioning/

jobs:
 xcsoar-docker-env:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGENAME: xcsoar-build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: True
      - name: Login to Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.actor }}
          password: ${{ github.token }}
      - name: build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ${{ github.repository }}/xcsoar-build:${{ env.IMAGE_TAG }}
          secrets: |
            GIT_AUTH_TOKEN=${{ github.token }}
