on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
 xcsoar-compile-unix:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGENAME: xcsoar-build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: True
      - run: echo ${{ secrets.GHRCIO }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
      - run: docker run --mount type=bind,source="$(pwd)",target=/opt/xcsoar -i ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGENAME }} xcsoar-compile UNIX

 xcsoar-compile-android:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGENAME: xcsoar-build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: True
      - run: echo ${{ secrets.GHRCIO }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
      - run: docker run --mount type=bind,source="$(pwd)",target=/opt/xcsoar -i ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGENAME }} xcsoar-compile ANDROID

 xcsoar-compile-win64:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghcr.io
      IMAGENAME: xcsoar-build
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: True
      - run: echo ${{ secrets.GHRCIO }} | docker login ${{ env.REGISTRY }} -u ${{ github.actor }} --password-stdin
      - run: docker run --mount type=bind,source="$(pwd)",target=/opt/xcsoar -i ${{ env.REGISTRY }}/${{ github.actor }}/${{ env.IMAGENAME }} xcsoar-compile WIN64
