on:
  workflow_dispatch:
  push:

jobs:
 compile-xcsoar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/lordfolken/xcsoar/xcsoar-build:master-447550a 
      - run: docker build ./ide/ --file ide/docker/Dockerfile --cache-from=docker.pkg.github.com/lordfolken/xcsoar/xcsoar-build:master-447550a -t docker.pkg.github.com/lordfolken/xcsoar/xcsoar-build 
      - run: docker images
      - run: docker push docker.pkg.github.com/lordfolken/xcsoar/xcsoar-build
      - run: docker exec docker.pkg.github.com/lordfolken/xcsoar/xcsoar-build xcsoar-compile UNIX 
      - run: docker exec docker.pkg.github.com/lordfolken/xcsoar/xcsoar-build xcsoar-compile ANDROID 
      - run: docker exec docker.pkg.github.com/lordfolken/xcsoar/xcsoar-build xcsoar-compile WIN64
