on:
  workflow_dispatch:
  push:

jobs:
 compile-xcsoar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: docker pull docker.pkg.github.com/$GITHUB_REPOSITORY/xcsoar/xcsoar-build || true
      - run: docker build ./ide/ --file ide/docker/Dockerfile -t xscoar-build --cache-from=docker.pkg.github.com/$GITHUB_REPOSITORY/xcsoar/xcsoar-build
      - run: docker tag xcsoar-build docker.pkg.github.com/$GITHUB_REPOSITORY/xcsoar && docker push docker.pkg.github.com/$GITHUB_REPOSITORY/xcsoar || true
      - run: docker exec docker.pkg.github.com/$GITHUB_REPOSITORY/xcsoar xcsoar-compile UNIX 
      - run: docker exec docker.pkg.github.com/$GITHUB_REPOSITORY/xcsoar xcsoar-compile ANDROID 
      - run: docker exec docker.pkg.github.com/$GITHUB_REPOSITORY/xcsoar xcsoar-compile WIN64
