on:
  workflow_dispatch:
  push:

jobs:
 compile-xcsoar:
    runs-on: ubuntu-latest
    env:
      REGISTRY: ghrc.io
      IMAGENAME: xcsoar-build
      OWNER: lordfolken
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login $REGISTRY -u $GITHUB_ACTOR --password-stdin
      - run: docker pull $REGISTRY/$OWNER/$IMAGENAME || true
      - run: docker build ./ide/ --file ide/docker/Dockerfile --cache-from=$REGISTRY/$OWNER/$IMAGENAME:master-447550a -t $REGISTRY/$OWNER/$IMAGENAME 
      - run: docker images
      - run: docker push $REGISTRY/$OWNER/$IMAGENAME
      - run: docker run $REGISTRY/$OWNER/$IMAGENAME "xcsoar-compile UNIX"
      - run: docker run $REGISTRY/$OWNER/$IMAGENAME "xcsoar-compile ANDROID"
      - run: docker run $REGISTRY/$OWNER/$IMAGENAME "xcsoar-compile WIN64"
