on:
  workflow_dispatch:
  push:

jobs:
 compile-xcsoar:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u $GITHUB_ACTOR --password-stdin
      - run: docker pull docker.pkg.github.com/${{ github.actor }}/xcsoar/xcsoar-build || true
      - run: docker build ./ide/ --file ide/docker/Dockerfile -t xscoar-build --cache-from=docker.pkg.github.com/${{ github.repository }}/xcsoar/xcsoar-build
      - run: docker tag xcsoar-build docker.pkg.github.com/${{ github.repository }}/xcsoar && docker push docker.pkg.github.com/${{ github.repository }}/xcsoar || true
      - run: docker exec docker.pkg.github.com/${{ github.repository }}/xcsoar xcsoar-compile UNIX 
      - run: docker exec docker.pkg.github.com/${{ github.repository }}/xcsoar xcsoar-compile ANDROID 
      - run: docker exec docker.pkg.github.com/${{ github.repository }}/xcsoar xcsoar-compile WIN64
