on:
  workflow_dispatch:
  push:

jobs:
 buildandpush:
   runs-on: ubuntu-latest
   steps:
    - uses: actions/checkout@v2
      name: Check out code
  
    - uses: mr-smithers-excellent/docker-build-push@v4
      name: push image
      with:
        image: ${{ github.actor }}/xcsoar-build
        registry: docker.pkg.github.com
        githubOrg: override-org # optional
        dockerfile: './ide/docker/Dockerfile'
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }} 
