on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
jobs:
  release:
    name: "Create Release"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: parse changelog
        run: echo ::set-env name=CHANGELOGENTRY::$(./tools/changelog.sh ${{ github.ref }})
        id: changelogentry
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ github.ref }}
          body: ${{ steps.changelogentry.outputs.CHANGELOGENTRY }}
